version: '3.8'

services:
  api_gateway:
    image: node
    container_name: homepage
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm start"
    secrets:
      - spoonacular_key
    environment:
      - NODE_ENV=development

secrets:
  spoonacular_key:
    file: ./spoonacular_key.txt

volumes:
  db_data:


networks:
  app_network:
    name: app_network
  profile_network:
    name: profile_network
