version: '3.8'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  api_gateway:
    image: node
    container_name: homepage
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    secrets:
      - spoonacular_key
    environment:
      - NODE_ENV=development

secrets:
  spoonacular_key:
    file: ./spoonacular_key.txt

volumes:
  db_data:


networks:
  app_network:
    name: app_network
