version: '3.8'

services:
  api_gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - 8080:8080
    networks:
      - app_network

  homepage:
    build: ./homepage
    container_name: homepage_service
    networks:
      - app_network

  chat:
    build: ./chat
    container_name: chat_service
    environment:
      - FIREBASE_CONFIG=your_firebase_chat_config
    networks:
      - app_network

  kulkasku:
    build: ./kulkasku
    container_name: kulkasku_service
    environment:
      - FIREBASE_CONFIG=your_firebase_kulkasku_config
    networks:
      - app_network

  profile:
    build: ./profile
    container_name: profile_service
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword123
      - DB_NAME=profile_db
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=profile_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
