version: '3.8'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 2222:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=rootpassword123
    depends_on:
      - db
    networks:
      - app_network

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  nodejs:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
