version: '3.8'

services:
  nodejs:
    image: bitnami/node
    container_name: chat-nodejs
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:3000"
    environment:
      - NODE_DB_HOST=db
      - NODE_DB_PORT=3306
      - NODE_DB_USER=root
      - NODE_DB_PASSWORD=yourpassword
      - NODE_DB_NAME=mydatabase
    networks:
      - app_network

networks:
  app_network:
    external: true
