version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "3306:3306"
    networks:
      - profile_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - profile_network

  nodejs:
    image: node:alpine
    container_name: profile-nodejs
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install mysql2 express && node index.js"
    ports:
      - "8300:8300"
    env_file: .env
    environment:
      NODE_DB_HOST: ${NODE_DB_HOST}
      NODE_DB_PORT: ${NODE_DB_PORT}
      NODE_DB_USER: ${NODE_DB_USER}
      NODE_DB_PASSWORD: ${NODE_DB_PASSWORD}
      NODE_DB_NAME: ${NODE_DB_NAME}
    depends_on:
      - db
    networks:
      - profile_network

volumes:
  db_data:


networks:
  profile_network:
