version: '3.8'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  nodejs:
    image: node
    container_name: profile-nodejs
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8300:8300"
    environment:
      - NODE_DB_HOST=db
      - NODE_DB_PORT=3306
      - NODE_DB_USER=root
      - NODE_DB_PASSWORD=yourpassword
      - NODE_DB_NAME=mydatabase

networks:
  profile_network:
    external: true
