
# services:
#   nodejs:
#     image: bitnami/node
#     container_name: homepage-nodejs
#     # restart: always
#     working_dir: /app
#     volumes:
#       - .:/app
#     ports:
#       - "8010:3000"
#     environment:
#       - NODE_DB_HOST=db
#       - NODE_DB_PORT=3306
#       - NODE_DB_USER=root
#       - NODE_DB_PASSWORD=yourpassword
#       - NODE_DB_NAME=mydatabase
#       - SPOONACULAR_API_KEY=/run/secrets/spoonacular_key # Mengakses secret sebagai variabel lingkungan

# networks:
#   app_network:
#     external: true

services:
  homepage:
    image: node:18
    container_name: homepage
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    secrets:
      - spoonacular_key
    environment:
      - NODE_ENV=development

secrets:
  spoonacular_key:
    file: ./spoonacular_key.txt

