version: '3.8'

services:
  golang:
    image: golang
    container_name: kulkasku-golang
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json
    command: go run main.go
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app_network:
    external: true
