version: '3.8'

services:
  golang:
    image: golang
    container_name: kulkasku-golang
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8200:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=laravel_user
      - DB_PASSWORD=laravel_password
      - DB_NAME=laravel

networks:
  app_network:
    external: true
